import {
  accountSchema,
  positionSchema,
  type Account,
  type Position,
} from "../../../src/domain/portfolio/index.js";
import { klineBarSchema, type KlineBar } from "../../../src/domain/market/index.js";

const DAY_MS = 24 * 60 * 60 * 1000;

export const REPLAY_SYMBOL = "000001";
export const REPLAY_MARKET = "SZSE" as const;

/**
 * Deterministic daily bars for the replay fixtures — a gentle linear uptrend over
 * weekdays from 2026-05-04 through 2026-06-22. The range gives >20 warmup bars
 * before the golden window (2026-06-18/19) so MA20 is defined, and includes bars
 * AFTER the window (up to 2026-06-22) to prove the as-of filter excludes the future.
 * Generated by formula (not hand-written JSON) so it is reproducible and reviewable.
 */
export function buildReplayBars(
  symbol: string = REPLAY_SYMBOL,
  market: "SSE" | "SZSE" = REPLAY_MARKET,
): KlineBar[] {
  const rawSymbol = `${market === "SZSE" ? "sz" : "sh"}${symbol}`;
  const startMs = Date.UTC(2026, 4, 4); // 2026-05-04
  const endMs = Date.UTC(2026, 5, 22); // 2026-06-22
  const bars: KlineBar[] = [];
  let index = 0;

  for (let ms = startMs; ms <= endMs; ms += DAY_MS) {
    const date = new Date(ms);
    const dayOfWeek = date.getUTCDay();
    if (dayOfWeek === 0 || dayOfWeek === 6) {
      continue; // skip weekends — no bar
    }

    const tradeDate = `${date.getUTCFullYear()}-${pad2(date.getUTCMonth() + 1)}-${pad2(date.getUTCDate())}`;
    const close = round2(10 + index * 0.1);
    const volume = 1_000_000 + index * 1000;

    bars.push(
      klineBarSchema.parse({
        symbol,
        market,
        provider: "tencent",
        period: "1d",
        tradeDate,
        open: round2(close - 0.05),
        close,
        high: round2(close + 0.08),
        low: round2(close - 0.08),
        volume,
        turnover: round2(close * volume),
        rawSymbol,
      }),
    );
    index += 1;
  }

  return bars;
}

export function replayBarsBySymbol(): Record<string, KlineBar[]> {
  return { [REPLAY_SYMBOL]: buildReplayBars() };
}

export function replayAccount(): Account {
  return accountSchema.parse({
    accountId: "paper-replay",
    type: "paper",
    baseCurrency: "CNY",
    initialCash: 100_000,
    cash: { available: 41_750, frozen: 0 },
    status: "active",
    createdAt: "2026-05-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  });
}

/** Held position WITHOUT an on-disk latestPrice — replay must mark-to-market from as-of bars only. */
export function replayPositions(): Position[] {
  return [
    positionSchema.parse({
      accountId: "paper-replay",
      symbol: REPLAY_SYMBOL,
      market: REPLAY_MARKET,
      name: "平安银行",
      quantity: 5_000,
      availableQuantity: 5_000,
      todayBuyQuantity: 0,
      frozenQuantity: 0,
      costPrice: 11.5,
      currency: "CNY",
      openedAt: "2026-05-10T01:00:00.000Z",
      updatedAt: "2026-05-10T01:00:00.000Z",
    }),
  ];
}

function pad2(value: number): string {
  return String(value).padStart(2, "0");
}

function round2(value: number): number {
  return Math.round(value * 100) / 100;
}
